# Docker Compose configuration for the 'alpha-photo-share' project.
services:
  redis:
    image: redis:8.0-rc1-alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "6379:6379"

  db:
    image: postgres:16.8-alpine3.21
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    
    depends_on:
      - redis
      - db
    volumes:
      - logs:/app/logs
    command: ["./scripts/entrypoint_backend.sh", ]

volumes:
  postgres_data:
  logs: