# Docker Compose configuration for the 'alpha-photo-share' project.
services:
  redis:
    image: redis:8.0-rc1-alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  db:
    image: postgres:16.8-alpine3.21
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always
    depends_on:
      - redis
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - logs:/app/logs
    command: ["./scripts/entrypoint_backend.sh"]

volumes:
  postgres_data:
  logs: